'use strict';

const express = require('express');
const fetch   = require('node-fetch');
const path    = require('path');

const app  = express();
const PORT = process.env.PORT || 3000;

app.use(express.json({ limit: '10mb' }));
app.use(express.static(path.join(__dirname, 'public')));

/* ── Prompt ─────────────────────────────────────────────────────────────── */

const SYSTEM_PROMPT = `You are an expert front-end developer and designer. Your job is to generate complete, beautiful, modern websites.

You MUST respond with ONLY a valid JSON object — no markdown fences, no explanation, no preamble, no prose.

Exact format:
{"files":{"index.html":"<!DOCTYPE html>...","style.css":"/* css */","script.js":"// js"}}

STRICT RULES:
1. index.html must be a complete, valid HTML5 document starting with <!DOCTYPE html>
2. style.css must be a full, modern CSS file — include variables, flexbox/grid, hover effects, transitions, media queries, good typography and color palette. Minimum 100 lines. DO NOT output weak or unstyled CSS.
3. script.js must be working JavaScript (empty string only if truly unnecessary)
4. ALL JSON string values must have special characters properly JSON-escaped (newlines as \\n, quotes as \\", backslashes as \\\\)
5. Generate a VISUALLY IMPRESSIVE, PRODUCTION-READY website — not a basic unstyled page
6. Use Google Fonts via @import or <link>, beautiful color palettes, smooth animations, responsive design
7. Output ONLY the JSON object. Nothing before or after it.`;

/* ── Fallback website returned when AI fails twice ───────────────────────── */

function makeFallbackFiles(prompt) {
  const title = prompt ? prompt.slice(0, 80).replace(/"/g, '&quot;') : 'Generated Website';
  return {
    'index.html': `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header class="hero">
    <div class="container">
      <h1>${title}</h1>
      <p>Your website could not be generated by the AI. Please try again with a different model or a clearer prompt.</p>
      <a class="btn" href="#">Try Again</a>
    </div>
  </header>
  <script src="script.js"></script>
</body>
</html>`,
    'style.css': `@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap');
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--primary:#6366f1;--bg:#0f0f1a;--surface:#1a1a2e;--text:#e2e8f0;--muted:#94a3b8}
body{font-family:'Inter',sans-serif;background:var(--bg);color:var(--text);min-height:100vh;display:flex;align-items:center;justify-content:center}
.container{max-width:640px;margin:0 auto;padding:0 24px;text-align:center}
.hero{width:100%;padding:80px 0}
h1{font-size:clamp(1.8rem,5vw,3rem);font-weight:800;letter-spacing:-0.04em;margin-bottom:16px;background:linear-gradient(135deg,#6366f1,#a78bfa);-webkit-background-clip:text;-webkit-text-fill-color:transparent}
p{color:var(--muted);line-height:1.75;margin-bottom:32px;font-size:1.05rem}
.btn{display:inline-flex;align-items:center;padding:14px 32px;background:var(--primary);color:#fff;border-radius:50px;font-weight:600;font-size:15px;text-decoration:none;transition:all .2s;box-shadow:0 4px 24px rgba(99,102,241,.4)}
.btn:hover{transform:translateY(-2px);box-shadow:0 8px 32px rgba(99,102,241,.6)}`,
    'script.js': '// Fallback page — no JS needed',
  };
}

/* ── Helpers ─────────────────────────────────────────────────────────────── */

function safeLog(label, value) {
  try {
    const str = typeof value === 'string' ? value : JSON.stringify(value);
    console.log(label, str.length > 500 ? str.slice(0, 500) + `… [+${str.length - 500} chars]` : str);
  } catch (_) {
    console.log(label, '[unserializable value]');
  }
}

function stripFences(text) {
  return text.trim()
    .replace(/^```(?:json)?\s*/i, '')
    .replace(/\s*```\s*$/i, '')
    .trim();
}

function extractJSON(raw) {
  if (!raw || typeof raw !== 'string') return null;

  const t = stripFences(raw);

  // Attempt 1: direct parse
  try { return JSON.parse(t); } catch (_) {}

  // Attempt 2: slice from first { to last }
  const s = t.indexOf('{');
  const e = t.lastIndexOf('}');
  if (s !== -1 && e > s) {
    try { return JSON.parse(t.slice(s, e + 1)); } catch (_) {}
  }

  // Attempt 3: find {"files": pattern specifically
  const filesIdx = t.indexOf('"files"');
  if (filesIdx !== -1) {
    const objStart = t.lastIndexOf('{', filesIdx);
    if (objStart !== -1) {
      // Try progressively shorter endings
      for (let end = t.length - 1; end > filesIdx; end--) {
        if (t[end] === '}') {
          try {
            const candidate = t.slice(objStart, end + 1);
            const parsed = JSON.parse(candidate);
            if (parsed && typeof parsed === 'object') return parsed;
          } catch (_) {}
        }
      }
    }
  }

  return null;
}

function validateFiles(files) {
  if (!files || typeof files !== 'object' || Array.isArray(files)) {
    return 'Response JSON is missing a valid "files" object.';
  }

  const indexHtml = files['index.html'];
  if (!indexHtml || typeof indexHtml !== 'string') {
    return 'Response is missing index.html.';
  }

  const trimmed = indexHtml.trim();
  if (trimmed.length < 50) {
    return 'index.html is too short to be a real HTML page.';
  }

  if (!/<html/i.test(trimmed)) {
    return 'index.html does not appear to contain valid HTML.';
  }

  return null; // valid
}

async function callOpenRouter(apiKey, model, messages, extraOptions = {}) {
  const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
      'HTTP-Referer': 'https://github.com/webforge-ai',
      'X-Title': 'WebForge AI'
    },
    body: JSON.stringify({
      model,
      messages,
      temperature: 0.2,
      max_tokens: 4000,
      ...extraOptions
    })
  });

  if (!res.ok) {
    const body = await res.text().catch(() => '');
    throw new Error(`OpenRouter ${res.status}: ${body.slice(0, 400)}`);
  }

  let data;
  try {
    data = await res.json();
  } catch (err) {
    throw new Error('OpenRouter returned non-JSON response: ' + err.message);
  }

  const content = data?.choices?.[0]?.message?.content;
  if (content === undefined || content === null) {
    safeLog('[callOpenRouter] Unexpected response shape:', data);
    throw new Error('Model returned empty or missing content field.');
  }
  if (typeof content !== 'string' || content.trim() === '') {
    throw new Error('Model returned blank content.');
  }

  return content;
}

/* ── GET /models ─────────────────────────────────────────────────────────── */

app.get('/models', async (req, res) => {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) {
    return res.status(500).json({ error: 'OPENROUTER_API_KEY not set', models: [] });
  }
  try {
    const response = await fetch('https://openrouter.ai/api/v1/models', {
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json'
      }
    });
    if (!response.ok) {
      throw new Error(`OpenRouter models API ${response.status}`);
    }
    const data = await response.json();
    const models = (data.data || [])
      .map(m => m.id)
      .filter(Boolean)
      .sort((a, b) => a.localeCompare(b));
    return res.json({ models });
  } catch (err) {
    console.error('[/models]', err.message);
    return res.status(500).json({ error: err.message, models: [] });
  }
});

/* ── POST /generate ──────────────────────────────────────────────────────── */

app.post('/generate', async (req, res) => {
  const { prompt, model } = req.body || {};

  if (!prompt?.trim()) return res.status(400).json({ error: 'Prompt is required' });
  if (!model?.trim())  return res.status(400).json({ error: 'Model is required' });

  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) return res.status(500).json({ error: 'OPENROUTER_API_KEY not set on server' });

  const messages = [
    { role: 'system', content: SYSTEM_PROMPT },
    {
      role: 'user',
      content: `Create a website: ${prompt.trim()}\n\nOutput ONLY the JSON object. No explanation. No markdown.`
    }
  ];

  let raw1, parsed;

  /* ── Attempt 1 ──────────────────────────────────────────────────────── */
  try {
    raw1 = await callOpenRouter(apiKey, model.trim(), messages);
    safeLog('[/generate] Attempt 1 raw (first 300):', raw1.slice(0, 300));
  } catch (err) {
    console.error('[/generate] Attempt 1 API call failed:', err.message);
    // Return fallback instead of empty response
    console.warn('[/generate] Returning fallback website after API failure');
    const fallback = makeFallbackFiles(prompt.trim());
    return res.json({ files: fallback, warning: 'AI call failed — showing placeholder page. ' + err.message });
  }

  parsed = extractJSON(raw1);

  /* ── Attempt 2 (retry if parse failed or files invalid) ─────────────── */
  if (!parsed || validateFiles(parsed.files)) {
    const reason = !parsed ? 'invalid JSON' : validateFiles(parsed.files);
    console.warn(`[/generate] Attempt 1 unusable (${reason}) — retrying`);

    const retryMessages = [
      ...messages,
      { role: 'assistant', content: raw1 },
      {
        role: 'user',
        content: 'Your previous response was not valid. You MUST respond with ONLY a raw JSON object matching this exact shape:\n{"files":{"index.html":"...","style.css":"...","script.js":"..."}}\nNo markdown, no code fences, no explanation. The JSON must be parseable. Start your response with { and end with }.'
      }
    ];

    let raw2;
    try {
      raw2 = await callOpenRouter(apiKey, model.trim(), retryMessages);
      safeLog('[/generate] Attempt 2 raw (first 300):', raw2.slice(0, 300));
      parsed = extractJSON(raw2);
    } catch (err) {
      console.error('[/generate] Attempt 2 API call failed:', err.message);
      // Fall through to fallback below
      parsed = null;
    }

    if (!parsed || validateFiles(parsed.files)) {
      const reason2 = !parsed ? 'still invalid JSON' : validateFiles(parsed.files);
      console.warn(`[/generate] Attempt 2 unusable (${reason2}) — returning fallback website`);
      const fallback = makeFallbackFiles(prompt.trim());
      return res.json({
        files: fallback,
        warning: `AI returned unusable output after 2 attempts (${reason2}). Showing placeholder. Try a smarter model (claude-3.5-sonnet, gpt-4o, gemini-pro-1.5).`
      });
    }
  }

  /* ── Normalise files ─────────────────────────────────────────────────── */
  const files = parsed.files;

  // Ensure index.html contains real HTML (not a placeholder)
  if (!files['index.html'] || !/<html/i.test(files['index.html'])) {
    files['index.html'] = makeFallbackFiles(prompt.trim())['index.html'];
  }

  if (typeof files['style.css'] !== 'string') {
    files['style.css'] = '';
  }

  if (typeof files['script.js'] !== 'string') {
    files['script.js'] = '';
  }

  // Guarantee files object always has all three keys
  if (!('index.html' in files)) files['index.html'] = makeFallbackFiles(prompt.trim())['index.html'];
  if (!('style.css'  in files)) files['style.css']  = '';
  if (!('script.js'  in files)) files['script.js']  = '';

  return res.json({ files });
});

/* ── Start ───────────────────────────────────────────────────────────────── */

app.listen(PORT, () => {
  console.log(`\n  ✅ WebForge AI running → http://localhost:${PORT}\n`);
});
